import Link from "next/link";
import { SiteShell } from "./site-shell";

export default function Home() {
  return <SiteShell><main>
    <section className="hero hero-home">
      <div className="hero-photo" role="img" aria-label="A residential street in Kingstanding, north Birmingham" /><div className="hero-wash" />
      <div className="wrap hero-content"><p className="eyebrow light">Churches serving churches</p><h1>Strengthening ministry<br />for the long haul.</h1><p className="hero-lede">We come alongside local church leaders to help turn ministry vision into sustainable action.</p><div className="button-row"><Link className="button gold" href="/our-work">Our work in Birmingham</Link><Link className="text-link light-link" href="/about">How we work <span aria-hidden="true">→</span></Link></div></div>
      <div className="hero-tagline">Serving Churches. <i>Equipping Disciples.</i> Advancing the Gospel.</div>
    </section>
    <section className="section intro-section"><div className="wrap narrow centered"><p className="eyebrow">Our posture</p><h2>Good ministry ideas often need more than good intentions.</h2><p className="large-copy">Church Mission Collaborative is a connector, catalyst, and extra set of hands—not a substitute for the local church. We listen first, then help churches build ministry that belongs to them.</p></div></section>
    <section className="section pillars-section"><div className="wrap"><div className="section-heading split-heading"><div><p className="eyebrow light">Our ministry model</p><h2 className="light">Serve. Build. Connect.</h2></div><p>Three commitments shape every collaboration.</p></div><div className="pillars"><article><span>01</span><h3>Serve</h3><p>We begin with the vision of local church leadership, learning the congregation and its community before deciding what help is useful.</p></article><article><span>02</span><h3>Build</h3><p>We bring energy, organization, coaching, and leadership for a season—always working toward local ownership and sustainability.</p></article><article><span>03</span><h3>Connect</h3><p>We help the distinctive gifts of one church cross congregational boundaries to strengthen another.</p></article></div></div></section>
    <section className="section birmingham-feature"><div className="wrap feature-grid"><div className="feature-image"><img src="/assets/photo-6.jpg" alt="Charlton Road Christian Church in Kingstanding, Birmingham" /></div><div className="feature-copy"><p className="eyebrow">Our first long-term collaboration</p><h2>Beginning in Birmingham.</h2><p>CMC’s first long-term collaboration is taking shape in Kingstanding, north Birmingham, alongside Charlton Road Christian Church.</p><p>Jeff and Laurie Ronk are relocating to become part of the church and community—listening, learning, building relationships, and adding capacity where it is useful.</p><Link className="text-link" href="/our-work">Explore the Birmingham collaboration <span aria-hidden="true">→</span></Link></div></div></section>
    <section className="section quote-band"><div className="wrap narrow centered"><p className="eyebrow light">The larger aim</p><blockquote>“For CMC, success looks like local churches becoming stronger—not CMC becoming indispensable.”</blockquote></div></section>
    <section className="section final-cta"><div className="wrap cta-grid"><div><p className="eyebrow">Come alongside</p><h2>Help make church-strengthening ministry possible.</h2></div><div><p>Financial support and prayer make it possible for CMC to live, listen, serve, and build for the long haul.</p><Link className="button navy" href="/support">Support CMC</Link></div></div></section>
  </main></SiteShell>;
}
